openapi: 3.0.3
info:
  title: Microgrid Simulator API
  version: 1.0.0
  description: Backend endpoint for the Microgrid Simulator Project
paths:
  /api/objects/objects/:
    get:
      operationId: objects_objects_list
      tags:
      - objects
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ObjectBaseModel'
          description: ''
    post:
      operationId: objects_objects_create
      tags:
      - objects
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectBaseModel'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ObjectBaseModel'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ObjectBaseModel'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectBaseModel'
          description: ''
  /api/objects/objects/{id}/:
    get:
      operationId: objects_objects_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this object base.
        required: true
      tags:
      - objects
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectBaseModel'
          description: ''
    put:
      operationId: objects_objects_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this object base.
        required: true
      tags:
      - objects
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectBaseModel'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ObjectBaseModel'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ObjectBaseModel'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectBaseModel'
          description: ''
    patch:
      operationId: objects_objects_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this object base.
        required: true
      tags:
      - objects
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedObjectBaseModel'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedObjectBaseModel'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedObjectBaseModel'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectBaseModel'
          description: ''
    delete:
      operationId: objects_objects_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this object base.
        required: true
      tags:
      - objects
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/projects/projects/:
    get:
      operationId: projects_projects_list
      tags:
      - projects
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
          description: ''
    post:
      operationId: projects_projects_create
      tags:
      - projects
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Project'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Project'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
          description: ''
  /api/projects/projects/{id}/:
    get:
      operationId: projects_projects_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this project.
        required: true
      tags:
      - projects
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
          description: ''
    put:
      operationId: projects_projects_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this project.
        required: true
      tags:
      - projects
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Project'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Project'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
          description: ''
    patch:
      operationId: projects_projects_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this project.
        required: true
      tags:
      - projects
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedProject'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedProject'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedProject'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
          description: ''
    delete:
      operationId: projects_projects_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this project.
        required: true
      tags:
      - projects
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    ObjectBaseModel:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 32
        polymorphic_ctype:
          type: integer
          readOnly: true
          nullable: true
        project:
          type: integer
      required:
      - id
      - polymorphic_ctype
      - project
    PatchedObjectBaseModel:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 32
        polymorphic_ctype:
          type: integer
          readOnly: true
          nullable: true
        project:
          type: integer
    PatchedProject:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 32
        date:
          type: string
          format: date-time
          nullable: true
    Project:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 32
        date:
          type: string
          format: date-time
          nullable: true
      required:
      - id
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
