"""Initial migration

Revision ID: 8626b2f68934
Revises: 
Create Date: 2024-11-15 21:50:42.259135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8626b2f68934'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EnergyIns', sa.Column('type', sa.Enum('Default', 'SolarPanel', 'WindTurbine', name='energyintype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EnergyIns', 'type')
    # ### end Alembic commands ###
