# Generated by Django 5.1.4 on 2024-12-15 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flowsheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Property Set')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('numeric', 'Numeric'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox'), ('segmented', 'Segmented'), ('text', 'Text')], default='numeric')),
                ('value', models.JSONField(blank=True, null=True)),
                ('key', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=64)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='objects.propertyset')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Object', max_length=32)),
                ('object_type', models.CharField(choices=[('solar_panel', 'Solarpanel'), ('wind_turbine', 'Windturbine'), ('factory_model', 'Factorymodel'), ('complex_home', 'Complexhome'), ('general_consumer', 'Generalconsumer'), ('lithium_ion', 'Lithiumion')], default='solar_panel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowsheet_objects', to='flowsheet.project')),
                ('property_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_owner', to='objects.propertyset')),
            ],
        ),
    ]
