# Generated by Django 5.1.4 on 2024-12-15 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet', '0001_initial'),
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_edge', to='flowsheet.project')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_node', to='objects.objectbase')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_node', to='objects.objectbase')),
            ],
        ),
    ]
