# Generated by Django 5.1.4 on 2024-12-09 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
    ]
