# Generated by Django 5.1.4 on 2024-12-15 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet', '0001_initial'),
        ('objects', '0002_edge'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name='edge',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_edges', to='flowsheet.project'),
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('solar_panel', 'Solarpanel'), ('wind_turbine', 'Windturbine'), ('factory_model', 'Factorymodel'), ('complex_home', 'Complexhome'), ('general_consumer', 'Generalconsumer'), ('lithium_ion', 'Lithiumion')], default='solar_panel')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_node', to='objects.propertyset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_nodes', to='flowsheet.project')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_node', to='objects.nodeposition')),
            ],
        ),
    ]
