# Generated by Django 5.1.4 on 2024-12-09 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_auto_20241209_0449'),
    ]

    operations = [
    ]
