# Generated by Django 5.1.4 on 2024-12-15 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_nodeposition_alter_edge_project_node'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectbase',
            old_name='object_type',
            new_name='type',
        ),
    ]
