# Generated by Django 5.1.4 on 2024-12-09 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_auto_20241209_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watts', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('daily_emissions', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('default', 'Default'), ('solar_panel', 'Solarpanel'), ('wind_turbine', 'Windturbine')], default='default')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='objects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
