# Generated by Django 5.1.4 on 2024-12-09 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_energyin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnergyIn',
        ),
    ]
