# Generated by Django 5.1.4 on 2024-12-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_rename_object_type_objectbase_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='name',
            field=models.CharField(default='New Object', max_length=64),
        ),
    ]
