# Generated by Django 5.1.4 on 2024-12-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_objectbase_energyin_energyout_energystorageunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectbase',
            name='name',
            field=models.CharField(default='New Object', max_length=32),
        ),
    ]
