# Generated by Django 5.1.4 on 2024-12-17 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_remove_node_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyinfo',
            old_name='type',
            new_name='display_type',
        ),
    ]
