# Generated by Django 5.1.4 on 2024-12-09 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_objectbase_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LithiumIonBattery',
            fields=[
                ('energystorageunit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.energystorageunit')),
                ('max_charge_rate', models.FloatField(default=0.0)),
                ('efficiency', models.FloatField(default=0.0)),
                ('current', models.IntegerField(default=0)),
                ('voltage', models.IntegerField(default=0)),
            ],
            bases=('objects.energystorageunit',),
        ),
    ]
