# Generated by Django 5.1.4 on 2024-12-09 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0008_lithiumionbattery'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarPanel',
            fields=[
                ('energyin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.energyin')),
                ('width', models.FloatField(default=0.0)),
                ('length', models.FloatField(default=0.0)),
                ('cells', models.IntegerField(default=0)),
                ('panel_type', models.CharField(choices=[('default', 'Default')], default='default')),
                ('material', models.CharField(choices=[('default', 'Default')], default='default')),
            ],
            bases=('objects.energyin',),
        ),
        migrations.CreateModel(
            name='WindTurbine',
            fields=[
                ('energyin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.energyin')),
                ('rotor_diameter', models.IntegerField(default=0)),
                ('rotation', models.IntegerField(default=0)),
                ('cut_in_speed', models.IntegerField(default=0)),
                ('rated_speed', models.IntegerField(default=0)),
                ('cut_off_speed', models.IntegerField(default=0)),
            ],
            bases=('objects.energyin',),
        ),
    ]
