# Generated by Django 5.1.4 on 2024-12-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0009_alter_edge_source_alter_edge_target_remove_node_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinfo',
            name='defined',
            field=models.BooleanField(default=False),
        ),
    ]
