# Generated by Django 5.1.4 on 2024-12-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0010_propertyinfo_defined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='isOpen',
        ),
        migrations.AddField(
            model_name='propertyset',
            name='formula',
            field=models.CharField(blank=True, null=True),
        ),
    ]
