# Generated by Django 5.1.4 on 2024-12-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0011_remove_node_isopen_propertyset_formula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='calculation_mode',
            field=models.CharField(choices=[('Power Based', 'Solarpowerbased'), ('Electrical', 'Electrical'), ('Physical', 'Physical')], default='Power Based'),
        ),
    ]
