# Generated by Django 5.1.4 on 2024-12-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0012_alter_node_calculation_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyset',
            name='formula',
            field=models.CharField(null=True),
        ),
    ]
