# Generated by Django 5.1.4 on 2024-12-27 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0013_alter_propertyset_formula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyset',
            name='formula',
        ),
        migrations.AlterField(
            model_name='node',
            name='calculation_mode',
            field=models.CharField(choices=[('Outputs', 'Outputs'), ('Advanced', 'Advanced'), ('Power Based', 'Solarpowerbased'), ('Peak Sunlight Hours', 'Solarpeaksunlighthours'), ('Electrical', 'Solarelectrical'), ('Physical', 'Solarphysical'), ('Power Output', 'Windpoweroutput'), ('Rotor Based', 'Windrotorbased'), ('Cut In/Out Speeds', 'Windcutincutoutspeeds')], default='Power Based'),
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_property', models.CharField(max_length=64)),
                ('formula_expression', models.CharField(max_length=256)),
                ('property_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='objects.propertyset')),
            ],
        ),
    ]
