# Generated by Django 5.1.4 on 2024-12-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0014_remove_propertyset_formula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinfo',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='calculation_mode',
            field=models.CharField(choices=[('Outputs', 'Outputs'), ('Advanced', 'Advanced'), ('Power Based', 'Solarpowerbased'), ('Peak Sunlight Hours', 'Solarpeaksunlighthours'), ('Electrical', 'Solarelectrical'), ('Physical', 'Solarphysical'), ('Power Output', 'Windpoweroutput'), ('Rotor Based', 'Windrotorbased'), ('Cut In/Out Speeds', 'Windcutincutoutspeeds'), ('Simple Home', 'Simplehome'), ('Complex Home', 'Complexhome')], default='Power Based'),
        ),
        migrations.AlterField(
            model_name='node',
            name='type',
            field=models.CharField(choices=[('solar_panel', 'Solarpanel'), ('wind_turbine', 'Windturbine'), ('factory_model', 'Factorymodel'), ('home', 'Home'), ('general_consumer', 'Generalconsumer'), ('lithium_ion', 'Lithiumion')], default='solar_panel'),
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='display_name',
            field=models.CharField(default='Unnamed', max_length=64),
        ),
    ]
