# Generated by Django 5.1.4 on 2025-01-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0015_propertyinfo_hidden_alter_node_calculation_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyinfo',
            name='set',
        ),
        migrations.AddField(
            model_name='propertyinfo',
            name='set',
            field=models.ManyToManyField(related_name='properties', to='objects.propertyset'),
        ),
    ]
