# Generated by Django 5.1.4 on 2025-01-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0016_remove_propertyinfo_set_propertyinfo_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyinfo',
            name='display_type',
            field=models.CharField(choices=[('numeric', 'Numeric'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox'), ('segmented', 'Segmented'), ('list', 'List'), ('text', 'Text')], default='numeric'),
        ),
    ]
