# Generated by Django 5.1.4 on 2025-01-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0017_alter_propertyinfo_display_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='calculation_mode',
            field=models.CharField(choices=[('Outputs', 'Outputs'), ('Advanced', 'Advanced'), ('Power Based', 'Solarpowerbased'), ('Peak Sunlight Hours', 'Solarpeaksunlighthours'), ('Electrical', 'Solarelectrical'), ('Physical', 'Solarphysical'), ('Power Output', 'Windpoweroutput'), ('Rotor Based', 'Windrotorbased'), ('Cut In/Out Speeds', 'Windcutincutoutspeeds'), ('Simple Home', 'Simplehome'), ('Complex Home', 'Complexhome'), ('Battery Capacity', 'Batterycapacity'), ('Battery Performance', 'Batteryperformance'), ('Battery Degradation', 'Batterydegradation'), ('Battery Lifecycle', 'Batterylifecycle'), ('Advanced Battery Metrics', 'Advancedbatterymetrics')], default='Power Based'),
        ),
    ]
