# Generated by Django 5.1.4 on 2025-01-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0020_alter_node_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='type',
            field=models.CharField(choices=[('solar_panel', 'Solarpanel'), ('wind_turbine', 'Windturbine'), ('factory_model', 'Factorymodel'), ('home', 'Home'), ('general_consumer', 'Generalconsumer'), ('lithium_ion', 'Lithiumion'), ('inverter', 'Inverter'), ('grid', 'Grid')], default='solar_panel'),
        ),
    ]
