"""Initial Migration

Revision ID: bf64ec172211
Revises: 
Create Date: 2024-12-07 22:49:08.923313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf64ec172211'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('EnergyOuts')
    op.add_column('EnergyIns', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'EnergyIns', 'Projects', ['project_id'], ['id'])
    op.add_column('EnergyStorageUnits', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'EnergyStorageUnits', 'Projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'EnergyStorageUnits', type_='foreignkey')
    op.drop_column('EnergyStorageUnits', 'project_id')
    op.drop_constraint(None, 'EnergyIns', type_='foreignkey')
    op.drop_column('EnergyIns', 'project_id')
    op.create_table('EnergyOuts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('watts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('daily_emissions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('Default', 'FactoryModel', 'ComplexHome', 'GeneralConsumer', name='energyouttype'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='EnergyOuts_pkey')
    )
    op.drop_table('Projects')
    # ### end Alembic commands ###
