from app.routes.EnergyInRoute import energy_in_router
from app.routes.SolarPanelRoute import solar_panel_router
from app.routes.WindTurbineRoute import wind_turbine_router
from app.routes.EnergyOutRoute import energy_out_router
from app.routes.ProjectRoute import project_router
from app.routes.EnergyStorageUnitRoute import energy_storage_router
from app.routes.LithiumIonBatteryRoute import lithium_ion_router