# Generated by Django 5.1.4 on 2025-01-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet', '0002_weatherdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='timeframe',
            field=models.CharField(choices=[('current', 'Current'), ('minutely', 'Minutely'), ('hourly', 'Hourly'), ('daily', 'Daily')], default='current'),
        ),
    ]
