# Generated by Django 5.1.4 on 2025-01-04 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet', '0003_weatherdata_timeframe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='irradiance',
            new_name='irradiance_dhi',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='irradiance_dni',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='irradiance_ghi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='sky',
            field=models.CharField(choices=[('cloudy_sky', 'Cloudy'), ('clear_sky', 'Clear')], default='clear_sky'),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='solar_timeframe',
            field=models.CharField(choices=[('daily', 'Daily'), ('hourly', 'Hourly')], default='daily'),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='sunrise',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='sunset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
