# Generated by Django 5.1.4 on 2025-01-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet', '0004_rename_irradiance_weatherdata_irradiance_dhi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='irradiance_dhi',
            new_name='irradiance',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='irradiance_dni',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='irradiance_ghi',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='solar_timeframe',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='sunrise',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='sunset',
        ),
    ]
