# Generated by Django 5.1.4 on 2025-01-04 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet', '0006_remove_weatherdata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_energy', models.FloatField(blank=True, null=True)),
                ('total_emissions', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(default=-37.719408)),
                ('longitude', models.FloatField(default=175.248599)),
                ('weather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_controller', to='flowsheet.weatherdata')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='controller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='controller_project', to='flowsheet.controller'),
            preserve_default=False,
        ),
    ]
