# Generated by Django 5.1.4 on 2025-01-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet', '0007_controller_project_controller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='controller',
            name='grid_emission_factor',
            field=models.FloatField(default=0.12),
        ),
    ]
