# Generated by Django 5.1.4 on 2025-01-05 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet', '0008_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='controller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='controller_project', to='flowsheet.controller'),
        ),
    ]
