# Generated by Django 5.1.4 on 2025-01-05 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet', '0009_alter_project_controller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='location',
        ),
    ]
