# Generated by Django 5.1.4 on 2025-01-12 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet', '0011_alter_controller_weather'),
        ('objects', '0016_remove_propertyinfo_set_propertyinfo_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='humidity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_humidity', to='objects.propertyinfo'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='irradiance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_irradiance', to='objects.propertyinfo'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='temperature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_temperature', to='objects.propertyinfo'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_speed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_wind_speed', to='objects.propertyinfo'),
        ),
    ]
