# Generated by Django 5.1.4 on 2025-01-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet', '0012_alter_weatherdata_humidity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='required_energy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
