# Generated by Django 5.1.4 on 2025-01-20 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowsheet', '0013_controller_required_energy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controller',
            old_name='required_energy',
            new_name='energy_produced',
        ),
        migrations.RenameField(
            model_name='controller',
            old_name='total_energy',
            new_name='energy_required',
        ),
    ]
